name: Docker Image CI

on:
  push:
    branches: [ "oauth2" ]
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Create an empty build context
      run: mkdir -p /tmp/empty

    - name: Build base image
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: |
          TEXLIVE_SCHEME=scheme-full
        context: /tmp/empty
        file: server-ce/Dockerfile-base
        tags: ghcr.io/lakelink/overleaf-base:latest
        push: true
        cache-from: type=gha
        cache-to: type=gha,mode=max

  build:
    runs-on: ubuntu-latest
    needs: build-base

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        registry: "ghcr.io"
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: latest

    - name: Build the image
      uses: docker/build-push-action@v3.2.0
      with:
        build-args: |
          OVERLEAF_BASE_TAG=ghcr.io/lakelink/overleaf-base:latest
          MONOREPO_REVISION=${{ github.sha }}
        file: server-ce/Dockerfile
        tags: ghcr.io/lakelink/overleaf-oauth2:latest
        push: true
